import json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
t = json.loads((root / "design/figma-tokens.json").read_text())
css = lambda name: name.replace("/", "-").replace(" ", "-").lower()
lines = ["/* generated by design/build_quarks.py */", ":root {"]
lines += [f"  --color-{css(k)}: {v};" for k, v in t["color"].items()]
lines += [f"  --{css(k)}: {v}px;" for k, v in t["space"].items()]
lines += [f"  --{css(k)}: {v}px;" for k, v in t["radius"].items()]
lines += [f"  --effect-{k}: {v};" for k, v in t["effect"].items()]
lines += [f"  --ios-{k}: {v};" for k, v in t["ios"].items()]
g = t["grid"]["desktop"]
lines += [f"  --grid-container: {g['container']}px;", f"  --grid-column: {g['column']}px;", f"  --grid-gutter: {g['gutter']}px;"]
# "SF Pro Text" по ширине совпадает с Figma, variable SF Pro — нет
lines += ['  --font-sf: "SF Pro", -apple-system, BlinkMacSystemFont, system-ui, sans-serif;',
          '  --font-sf-text: "SF Pro Text", "SF Pro", -apple-system, BlinkMacSystemFont, system-ui, sans-serif;', "}", ""]
for s in t["text"]:
    wdth = 132 if s["family"] == "expanded" else 100
    lines += [f".text-{css(s['name'])} {{",
              f"  font-family: var(--font-sf{'' if wdth == 132 else '-text'}); font-weight: {s['wght']}; font-size: {s['size']}px; line-height: {s['lh']}px; letter-spacing: {s['ls']};",
              f"  font-variation-settings: \"wdth\" {wdth};" + (" font-stretch: 132%;" if wdth == 132 else ""), "}"]
(root / "app/assets/stylesheets/00_quarks.css").write_text("\n".join(lines) + "\n")
print("ok", len(t["color"]), "colors,", len(t["text"]), "text styles")
